#!/bin/sh
set -e

# Lets x-terminal-emulator, which runs Terminal=true applications, open this terminal.
if [ "$1" = "configure" ]; then
    update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator /usr/bin/cutefish-terminal 40
fi

#DEBHELPER#
